"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

@dataclass(init=True)
class StackMove:
    num_items: int
    from_stack: int
    to_stack: int
    ...

def parse_move(line: str) -> Optional[StackMove]: ...
def parse_stack_level(line: str) -> List[str]: ...
def parse_stacks_and_moves(input_path: Path) -> Tuple[Dict[int, List[str]], List[StackMove]]: ...
def solve_part_1(input_path: Optional[Path]) -> Any: ...
def solve_part_2(input_path: Optional[Path]) -> Any: ...
