"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Optional
from exc import not_implemented

@not_implemented
def solve_part_1(input_path: Optional[Path]) -> Any: ...
@not_implemented
def solve_part_2(input_path: Optional[Path]) -> Any: ...
