"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Any, List, Optional

@dataclass
class Elf:
    calories: int = ...

def get_elves(input_path: Path) -> List[Elf]: ...
def solve_part_1(input_path: Optional[Path]) -> Any: ...
def solve_part_2(input_path: Optional[Path]) -> Any: ...
