"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, List, Optional

CHECK_SIGNAL_CYCLE_IDXS = ...
ROW_UPDATE_CYCLES = ...

@dataclass(init=True)
class InstructionInstance:
    instruction: Instruction
    value: int
    ...

class Instruction(Enum):
    @dataclass(init=True)
    class Value:
        num_cycles: int
        name: str
        ...

    NO_OP = ...
    ADD_X = ...

def parse_program(lines: List[str]) -> List[InstructionInstance]: ...
def solve_part_1(input_path: Optional[Path]) -> Any: ...
def solve_part_2(input_path: Optional[Path]) -> Any: ...
